# Generated by Django 5.0.2 on 2024-02-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredphoto',
            options={'verbose_name_plural': 'featuredPhotos'},
        ),
    ]
