# Generated by Django 5.0.2 on 2024-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(max_length=254, upload_to='photos'),
        ),
    ]
