# Generated by Django 5.0.2 on 2024-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(max_length=254, upload_to='https://your-bucket.s3.amazonaws.com/your-bucket/'),
        ),
    ]
