# Generated by Django 5.0.2 on 2024-02-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(max_length=254, upload_to='https://s3.eu-north-1.amazonaws.com//unit4project-blog/'),
        ),
    ]
