# Generated by Django 5.0.2 on 2024-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(max_length=254, upload_to='add_photo/'),
        ),
    ]
