# Generated by Django 5.0.2 on 2024-02-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
    ]
