# Generated by Django 5.0.2 on 2024-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'photos'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(max_length=254, upload_to=''),
        ),
    ]
