# Generated by Django 5.0.2 on 2024-02-28 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_comment_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=254, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.post')),
            ],
            options={
                'verbose_name_plural': 'photos',
            },
        ),
    ]
