# Generated by Django 5.0.2 on 2024-02-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_alter_featuredphoto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.post'),
        ),
    ]
