# Generated by Django 5.0.2 on 2024-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='look',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='look',
            name='photo',
        ),
        migrations.AddField(
            model_name='look',
            name='url',
            field=models.ImageField(default=1, max_length=254, upload_to=''),
            preserve_default=False,
        ),
    ]
